name: Build app and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: go build
        run: go build && mkdir ./dist
      - name: Prepare
        run: cp -r ./basic ./dist/ && cp -r ./static ./dist/static
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          SOURCE: "./dist"
          REMOTE_HOST: "118.190.37.169"
          # 用户
          REMOTE_USER: "root"
          TARGET: "/root/web/anthhub/deploy/gin-train-ticket"
      - name: Setup
        timeout-minutes: 10
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "118.190.37.169"
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: cd /root/web/anthhub/deploy/gin-train-ticket/dist && nohup ./basic &
